// Code generated by MockGen. DO NOT EDIT.
// Source: update.go
//
// Generated by this command:
//
//	mockgen -source=update.go -destination=update_mock_test.go -package=handler_test
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateMetricProcessor is a mock of UpdateMetricProcessor interface.
type MockUpdateMetricProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateMetricProcessorMockRecorder
	isgomock struct{}
}

// MockUpdateMetricProcessorMockRecorder is the mock recorder for MockUpdateMetricProcessor.
type MockUpdateMetricProcessorMockRecorder struct {
	mock *MockUpdateMetricProcessor
}

// NewMockUpdateMetricProcessor creates a new mock instance.
func NewMockUpdateMetricProcessor(ctrl *gomock.Controller) *MockUpdateMetricProcessor {
	mock := &MockUpdateMetricProcessor{ctrl: ctrl}
	mock.recorder = &MockUpdateMetricProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateMetricProcessor) EXPECT() *MockUpdateMetricProcessorMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockUpdateMetricProcessor) Update(method, name, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", method, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUpdateMetricProcessorMockRecorder) Update(method, name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateMetricProcessor)(nil).Update), method, name, value)
}
