// Code generated by MockGen. DO NOT EDIT.
// Source: update.go
//
// Generated by this command:
//
//	mockgen -source=update.go -destination=update_mock_test.go -package=handler_test
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricProcessor is a mock of MetricProcessor interface.
type MockMetricProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockMetricProcessorMockRecorder
	isgomock struct{}
}

// MockMetricProcessorMockRecorder is the mock recorder for MockMetricProcessor.
type MockMetricProcessorMockRecorder struct {
	mock *MockMetricProcessor
}

// NewMockMetricProcessor creates a new mock instance.
func NewMockMetricProcessor(ctrl *gomock.Controller) *MockMetricProcessor {
	mock := &MockMetricProcessor{ctrl: ctrl}
	mock.recorder = &MockMetricProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricProcessor) EXPECT() *MockMetricProcessorMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockMetricProcessor) Update(method, name, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", method, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMetricProcessorMockRecorder) Update(method, name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMetricProcessor)(nil).Update), method, name, value)
}
