// Code generated by MockGen. DO NOT EDIT.
// Source: update.go
//
// Generated by this command:
//
//	mockgen -source=update.go -destination=update_mock_test.go -package=handler_test
//

// Package handler_test is a generated GoMock package.
package handler_test

import (
	http "net/http"
	reflect "reflect"

	params "github.com/EvgeniyAleksandrov/metrics-server/internal/handler/request/params"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateMetricProcessor is a mock of UpdateMetricProcessor interface.
type MockUpdateMetricProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateMetricProcessorMockRecorder
	isgomock struct{}
}

// MockUpdateMetricProcessorMockRecorder is the mock recorder for MockUpdateMetricProcessor.
type MockUpdateMetricProcessorMockRecorder struct {
	mock *MockUpdateMetricProcessor
}

// NewMockUpdateMetricProcessor creates a new mock instance.
func NewMockUpdateMetricProcessor(ctrl *gomock.Controller) *MockUpdateMetricProcessor {
	mock := &MockUpdateMetricProcessor{ctrl: ctrl}
	mock.recorder = &MockUpdateMetricProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateMetricProcessor) EXPECT() *MockUpdateMetricProcessorMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockUpdateMetricProcessor) Update(updateParams params.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", updateParams)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUpdateMetricProcessorMockRecorder) Update(updateParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateMetricProcessor)(nil).Update), updateParams)
}

// MockUpdateParamsParser is a mock of UpdateParamsParser interface.
type MockUpdateParamsParser struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateParamsParserMockRecorder
	isgomock struct{}
}

// MockUpdateParamsParserMockRecorder is the mock recorder for MockUpdateParamsParser.
type MockUpdateParamsParserMockRecorder struct {
	mock *MockUpdateParamsParser
}

// NewMockUpdateParamsParser creates a new mock instance.
func NewMockUpdateParamsParser(ctrl *gomock.Controller) *MockUpdateParamsParser {
	mock := &MockUpdateParamsParser{ctrl: ctrl}
	mock.recorder = &MockUpdateParamsParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateParamsParser) EXPECT() *MockUpdateParamsParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockUpdateParamsParser) Parse(req *http.Request) (*params.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", req)
	ret0, _ := ret[0].(*params.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockUpdateParamsParserMockRecorder) Parse(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockUpdateParamsParser)(nil).Parse), req)
}

// MockUpdateResponseWriter is a mock of UpdateResponseWriter interface.
type MockUpdateResponseWriter struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateResponseWriterMockRecorder
	isgomock struct{}
}

// MockUpdateResponseWriterMockRecorder is the mock recorder for MockUpdateResponseWriter.
type MockUpdateResponseWriterMockRecorder struct {
	mock *MockUpdateResponseWriter
}

// NewMockUpdateResponseWriter creates a new mock instance.
func NewMockUpdateResponseWriter(ctrl *gomock.Controller) *MockUpdateResponseWriter {
	mock := &MockUpdateResponseWriter{ctrl: ctrl}
	mock.recorder = &MockUpdateResponseWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateResponseWriter) EXPECT() *MockUpdateResponseWriterMockRecorder {
	return m.recorder
}

// WriteBody mocks base method.
func (m *MockUpdateResponseWriter) WriteBody(resp http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBody", resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBody indicates an expected call of WriteBody.
func (mr *MockUpdateResponseWriterMockRecorder) WriteBody(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBody", reflect.TypeOf((*MockUpdateResponseWriter)(nil).WriteBody), resp)
}

// WriteError mocks base method.
func (m *MockUpdateResponseWriter) WriteError(resp http.ResponseWriter, err string, code int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteError", resp, err, code)
}

// WriteError indicates an expected call of WriteError.
func (mr *MockUpdateResponseWriterMockRecorder) WriteError(resp, err, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteError", reflect.TypeOf((*MockUpdateResponseWriter)(nil).WriteError), resp, err, code)
}

// WriteHeaders mocks base method.
func (m *MockUpdateResponseWriter) WriteHeaders(resp http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteHeaders", resp)
}

// WriteHeaders indicates an expected call of WriteHeaders.
func (mr *MockUpdateResponseWriterMockRecorder) WriteHeaders(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteHeaders", reflect.TypeOf((*MockUpdateResponseWriter)(nil).WriteHeaders), resp)
}
