// Code generated by MockGen. DO NOT EDIT.
// Source: counter.go
//
// Generated by this command:
//
//	mockgen -source=counter.go -destination=counter_mock_test.go -package=method_test
//

// Package method_test is a generated GoMock package.
package method_test

import (
	reflect "reflect"

	types "github.com/EvgeniyAleksandrov/metrics-server/internal/metric/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCounterStorage is a mock of CounterStorage interface.
type MockCounterStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCounterStorageMockRecorder
	isgomock struct{}
}

// MockCounterStorageMockRecorder is the mock recorder for MockCounterStorage.
type MockCounterStorageMockRecorder struct {
	mock *MockCounterStorage
}

// NewMockCounterStorage creates a new mock instance.
func NewMockCounterStorage(ctrl *gomock.Controller) *MockCounterStorage {
	mock := &MockCounterStorage{ctrl: ctrl}
	mock.recorder = &MockCounterStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterStorage) EXPECT() *MockCounterStorageMockRecorder {
	return m.recorder
}

// CounterAdd mocks base method.
func (m *MockCounterStorage) CounterAdd(name string, value types.Counter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CounterAdd", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// CounterAdd indicates an expected call of CounterAdd.
func (mr *MockCounterStorageMockRecorder) CounterAdd(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CounterAdd", reflect.TypeOf((*MockCounterStorage)(nil).CounterAdd), name, value)
}

// CounterGet mocks base method.
func (m *MockCounterStorage) CounterGet(name string) (types.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CounterGet", name)
	ret0, _ := ret[0].(types.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CounterGet indicates an expected call of CounterGet.
func (mr *MockCounterStorageMockRecorder) CounterGet(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CounterGet", reflect.TypeOf((*MockCounterStorage)(nil).CounterGet), name)
}

// GetAllCounterValues mocks base method.
func (m *MockCounterStorage) GetAllCounterValues() (map[string]types.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCounterValues")
	ret0, _ := ret[0].(map[string]types.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCounterValues indicates an expected call of GetAllCounterValues.
func (mr *MockCounterStorageMockRecorder) GetAllCounterValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCounterValues", reflect.TypeOf((*MockCounterStorage)(nil).GetAllCounterValues))
}
