// Code generated by MockGen. DO NOT EDIT.
// Source: gauge.go
//
// Generated by this command:
//
//	mockgen -source=gauge.go -destination=gauge_mock_test.go -package=method_test
//

// Package method_test is a generated GoMock package.
package method_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGaugeStorage is a mock of GaugeStorage interface.
type MockGaugeStorage struct {
	ctrl     *gomock.Controller
	recorder *MockGaugeStorageMockRecorder
	isgomock struct{}
}

// MockGaugeStorageMockRecorder is the mock recorder for MockGaugeStorage.
type MockGaugeStorageMockRecorder struct {
	mock *MockGaugeStorage
}

// NewMockGaugeStorage creates a new mock instance.
func NewMockGaugeStorage(ctrl *gomock.Controller) *MockGaugeStorage {
	mock := &MockGaugeStorage{ctrl: ctrl}
	mock.recorder = &MockGaugeStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGaugeStorage) EXPECT() *MockGaugeStorageMockRecorder {
	return m.recorder
}

// GaugeSet mocks base method.
func (m *MockGaugeStorage) GaugeSet(name string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GaugeSet", name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// GaugeSet indicates an expected call of GaugeSet.
func (mr *MockGaugeStorageMockRecorder) GaugeSet(name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GaugeSet", reflect.TypeOf((*MockGaugeStorage)(nil).GaugeSet), name, value)
}
